name: Build OpenWrt x86_64 6.6
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
env:
  TZ: Asia/Shanghai
  REPO_URL: https://github.com/openwrt/openwrt.git
  CONFIG_FILE: .config
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
    - name: 初始化工作目录
      run: |
        [ -d openwrt ] || git clone $REPO_URL
        cd openwrt && git pull
        ln -sf ../*/.config .config 2>/dev/null || true
    - name: 安装依赖
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib \
          gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev \
          file wget curl
    - name: 执行 DIY 脚本
      working-directory: ./openwrt
      run: |
        [ -f ../diy-part1.sh ] && bash ../diy-part1.sh
        [ -f ../diy-part2.sh ] && bash ../diy-part2.sh
    - name: 更新 feeds
      working-directory: ./openwrt
      run: |
        ./scripts/feeds clean
        ./scripts/feeds update -a
        # 关键修正步骤
        echo "=== 开始执行目录结构修正 ==="
        ${{ github.workspace }}/fix_dirs.sh
        echo "=== 目录修正完成 ==="
    - name: 安装 feeds
      working-directory: ./openwrt
      run: ./scripts/feeds install -a
    - name: 生成配置文件
      working-directory: ./openwrt
      run: |
        if [ -f "../$CONFIG_FILE" ]; then
          cp ../$CONFIG_FILE .
        else
          make defconfig
          ./scripts/diffconfig.sh > diffconfig
        fi
    - name: 下载依赖
      working-directory: ./openwrt
      run: make -j8 download
    - name: 编译固件
      working-directory: ./openwrt
      run: |
        echo "编译开始时间: $(date)"
        make -j$(nproc) V=s
        echo "编译结束时间: $(date)"
      env:
        SKIP_SAVE_CONFIG: 1
    - name: 上传编译成果
      uses: actions/upload-artifact@v4
      with:
        name: OpenWrt-Build-Artifacts
        path: |
          openwrt/bin/targets/x86/64/*
          openwrt/.config
        retention-days: 7
    - name: 清理工作空间
      if: always()
      run: |
        rm -rf openwrt/tmp
        rm -rf openwrt/logs
